# Generated by Django 5.1.6 on 2025-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('posted', 'posted')], default='draft', max_length=100),
        ),
    ]
