# Generated by Django 5.1.6 on 2025-04-20 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0002_remove_stockdetails_user_stockdetails_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockdetails',
            unique_together={('user', 'stock')},
        ),
    ]
